// in this file i made array that has a lots of word
// the usage is in index.html and it is a repository for find a random text
const words = [
    'a', 'lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur', 'adipiscing', 'elit',
    'sed', 'do', 'eiusmod', 'tempor', 'incididunt', 'ut', 'labore', 'et', 'dolore',
    'magna', 'aliqua', 'ut', 'enim', 'ad', 'minim', 'veniam', 'quis', 'nostrud',
    'exercitation', 'ullamco', 'laboris', 'nisi', 'ut', 'aliquip', 'ex', 'ea', 'commodo',
    'consequat', 'duis', 'aute', 'irure', 'dolor', 'in', 'reprehenderit', 'in', 'voluptate','majid' ,
    'velit', 'esse', 'cillum', 'dolore', 'eu', 'fugiat', 'nulla', 'pariatur', 'excepteur',
    'sint', 'occaecat', 'cupidatat', 'non', 'proident', 'sunt', 'in', 'culpa', 'qui',
    'officia', 'deserunt', 'mollit', 'anim', 'id', 'est', 'laborum', 'hello', 'world',
    'example', 'text', 'random', 'words', 'generate', 'python', 'code', 'script',
    'variable', 'function', 'loop', 'condition', 'array', 'object', 'class', 'method',
    'instance', 'data', 'structure', 'algorithm', 'programming', 'developer',
    'computer', 'software', 'hardware', 'database', 'query', 'server', 'client',
    'network', 'protocol', 'internet', 'website', 'browser', 'domain', 'hosting',
    'email', 'message', 'attachment', 'cloud', 'storage', 'security', 'password',
    'authentication', 'encryption', 'access', 'control', 'backup', 'restore',
    'virtual', 'machine', 'container', 'docker', 'kubernetes', 'system', 'interface',
    'user', 'experience', 'design', 'graphics', 'image', 'video', 'audio', 'file',
    'document', 'spreadsheet', 'presentation', 'collaboration', 'team', 'project',
    'management', 'task', 'deadline', 'meeting', 'communication', 'chat', 'forum',
    'social', 'media', 'platform', 'networking', 'profile', 'settings', 'privacy',
    'policy', 'terms', 'agreement', 'subscription', 'payment', 'checkout',
    'cart', 'shopping', 'ecommerce', 'business', 'marketing', 'advertisement',
    'campaign', 'strategy', 'sales', 'customer', 'feedback', 'support', 'service',
    'helpdesk', 'ticket', 'resolution', 'quality', 'performance', 'optimization',
    'analytics', 'report', 'insights', 'dashboard', 'monitoring', 'logging', 'debugging',
    'testing', 'deployment', 'release', 'version', 'update', 'upgrade', 'patch',
    'bug', 'fix', 'error', 'issue', 'problem', 'solution', 'learning', 'education',
    'course', 'tutorial', 'lesson', 'study', 'homework', 'assignment', 'exam', 'grade',
    'score', 'certificate', 'degree', 'college', 'university', 'research', 'publication',
    'article', 'book', 'library', 'catalog', 'review', 'rating', 'comment', 'discussion',
    'community', 'event', 'conference', 'workshop', 'seminar', 'speaker', 'presentation',
    'session', 'agenda', 'register', 'attendee', 'participant', 'networking', 'opportunity'
];